version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: configleak-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: configleak-redis
    restart: always
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]

  asynqmon:
    image: hibiken/asynqmon
    container_name: configleak-asynqmon
    platform: linux/amd64
    ports:
      - "8080:8080"
    command:
      - "-redis-url"
      - "redis://:${REDIS_PASSWORD}@redis:6379"
    depends_on:
      - redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}

volumes:
  pgdata:
